name: gxit_2025
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.12+24

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  glass_kit: ^4.0.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  lottie: ^3.3.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_crashlytics: ^4.0.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.7
  geolocator: ^14.0.1
  flutter_contacts: ^1.1.7+1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.4
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
